<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SignService.Common.HashSignature</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>7.3</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="SignService.Common.HashSignature.Pdf\**" />
    <EmbeddedResource Remove="SignService.Common.HashSignature.Pdf\**" />
    <None Remove="SignService.Common.HashSignature.Pdf\**" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Xml" />
    <Reference Include="System.Security">
      <Aliases>gb</Aliases>
    </Reference>
    <Reference Include="System.Security.Custom">
      <HintPath>..\System.Security.Custom.dll</HintPath>
    </Reference>
    <Reference Include="BouncyCastle.Crypto">
      <HintPath>..\BouncyCastle.Crypto.dll</HintPath>
    </Reference>
    <Reference Include="System.Net.Http">
      <HintPath>..\System.Net.Http.dll</HintPath>
    </Reference>
    <Reference Include="System.Text.Json">
      <HintPath>..\System.Text.Json.dll</HintPath>
    </Reference>
    <Reference Include="WindowBaseExt">
      <HintPath>..\WindowBaseExt.dll</HintPath>
    </Reference>
    <Reference Include="itextsharp">
      <HintPath>..\itextsharp.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
  </ItemGroup>
</Project>